services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - DATABASE_URL=mysql://AndresQuintero:ANDRESquintero2024@186.64.123.246:3306/assistant
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    env_file:
      - .env
